-- 1. Find the First and Last Movie Released Each Year
-- Retrieve the first and last movie released in each year. Display the year, first movie title, and last movie title.
SELECT  strftime ('%Y', release_date) AS year,
min(title) AS first_movie,
max(title) AS last_movie
FROM movies
GROUP BY year;

-- 2. Total Revenue Generated Each Year
-- Calculate the total revenue generated by movies released in each year. Display the year and total revenue, ordered by revenue in descending order.
SELECT  strftime ('%Y', release_date) AS year,
SUM(revenue) AS total_revenue
FROM movies
GROUP BY year
ORDER BY total_revenue DESC;

-- 3. Movies Released in the First Half of the Year
-- Find all movies that were released between January and June. Display the movie title, release date, and director name.
SELECT title,
release_date,
directors.name AS director_name
FROM movies
JOIN directors
ON movies.director_id = directors.id
WHERE CAST(strftime("%m",  release_date) AS INTEGER) BETWEEN 1 AND 6;

-- 4. Number of Movies Released on Weekends
-- Count the total number of movies released on a weekend (Saturday or Sunday). Use SQLite's strftime('%w') to determine the day of the week (0 = Sunday, 6 = Saturday).
SELECT count(*) AS weekend_movies
FROM movies
WHERE strftime ('%w', release_date) IN ('0', '6');

-- 5. Categorize Directors Based on Total Revenue
-- Classify directors based on the total revenue of their movies:
-- High Revenue if total revenue > $1 billion
-- Moderate Revenue if total revenue is between $500 million and $1 billion
-- Low Revenue if total revenue < $500 million
SELECT directors.name,
 sum(movies.revenue) AS total_revenue,
 CASE
	WHEN sum(movies.revenue) > 1000000000 THEN 'High Revenue'
	WHEN sum(movies.revenue) >= 500000000 THEN 'Moderate Revenue'
	ELSE 'Low Revenue'
END AS revenue_category
FROM movies
JOIN directors 
ON movies.director_id = directors.id
GROUP BY directors.name;

-- 6. Movies Based on Popularity and Revenue
-- Classify movies into the following categories based on popularity and revenue:
-- Blockbuster if popularity > 100 and revenue > $500 million
-- Hit if popularity > 50 and revenue between $100 million and $500 million
-- Average for all other movies
SELECT title,
popularity,
revenue,
CASE
	WHEN popularity > 100 AND revenue > 500000000 THEN 'Blockbuster'
	WHEN popularity > 50 AND revenue BETWEEN 100000000 AND  500000000 THEN 'Hit'
	ELSE 'Average'
END AS popularity_category
FROM movies;

-- 7. Directors with Critically Acclaimed and Poorly Rated Movies
-- List directors and count how many of their movies fall into these categories:
-- Critically Acclaimed if vote_average >= 8
-- Poorly Rated if vote_average < 5
SELECT directors.name,
sum(CASE 
	WHEN movies.vote_average >= 8 THEN 1 
	ELSE 0 
END) AS critically_acclaimed,
sum(CASE 
	WHEN movies.vote_average < 5 THEN 1 
	ELSE 0 
END) AS poorly_rated
FROM movies
JOIN directors 
ON movies.director_id = directors.id
GROUP BY directors.name;




